### ISSUE TITLE
Enhance the Program/Display view

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#15]
Here is a copy of the data files folder from the Demo environment, for reference.  [Data-Files-Lotus.zip](https://github.com/InSite/Lotus/files/271795/Data-Files-Lotus.zip)

1. Add a program selector above the Keyword search criteria field on the Program/Display view so you can select a program without being required to navigate back to the Admin page.

2. Add a user selector below the program selector. By default you (as current user) should be selected.

3. For each activity in the tree, query the selected user's plan for a matching task.  If a task is found, and if the user has successfully completed it (IsComplete && IsSuccess) then display a label-success beside the activity title with an icon (fa-check) and the score (%).  If the user unsuccessfully completed it (IsComplete && !IsSuccess) then display a label-danger element with an icon (fa-times) and the score.

4. For each activity in the tree, query the Graph for outgoing edges.  Display a small label beside the activity title for each edge: 

   [Condition] Descriptor ToActivity.Subtype: ToActivity.Title

5. For each activity in the tree, query the Graph for incoming edges.  Display a small label beside the activity title for each edge: 

   [Condition] Invert(Descriptor) FromActivity.Subtype: FromActivity.Title

   Where Invert("contains") = "is contained by"; Invert("requires") = "is required by"; Invert("satisfies") = "is satisfied by"; Invert("triggers") = "is triggered by"

6. For each activity referenced in an edge label, query the selected user's plan for a matching task.  

   - If a task is found, and if the user has successfully completed the task (IsComplete && IsSuccess) then include an icon (fa-check) and apply the "success" CSS class to the label.

   - If a task is found, and if the user has unsuccessfully completed the task (IsComplete && !IsSuccess) then include an icon (fa-times) and apply the "danger" CSS class to the label.

   - If no matching task is found, then apply the "info" CSS class to the label.

This will enable an administrator to see all activities (and closely related activities) completed by a user on one page.  Note that programs will often contain activities that have edges to (and from) activities in other programs. This is an important feature of our solution, so we should test for this scenario.

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
It's looking good so far.  There are some fixes and improvements we should make.  Most important, we can exclude edges where Descriptor = "is in" because this relationship is clear from the hierarchical layout on the page itself.  For example, we don't need to see a label for Applied Mathematics "is in Competency: SI

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
OK, thanks - this looks much better now. I think we might still have a bug in our code. For example, sign in using bcit@insitesystems.com/lotus and go to this page --

https://demo-lotus.insitesystems.com/program/display/22303

Expand Learning Goals Part B, then expand Air Conditioning. Notice the label beside Coil Types says "is satisfied by Competency: Competency 0176 SOPEEC Part B Section L - v". 

However, when you look at this activity in Shift iQ you will see that the relationship is defined from 5178 to 0176: "This Competency (5178) satisfies Competency 0176"

https://demo-shift.insitesystems.com/admin/activity/edit?id=22451

So it looks like the Program/Display has the edge direction backwards.

**Comment by Oleg-Terzi** [comment]
I fixed the bug.
